### ISSUE TITLE
REQUEST some option for + corners

### ISSUE THREAD

**Issue by fourjay** [dhobsd/asciitosvg#7]
AsciiFlow is a great way to build the boxes, but it seems fixed on using ``+`` corners. Manually editing an AsciiFlow exported diagram is fairly laborious and error prone. I'd love this process to be smoother :-)

**Comment by dhobsd** [comment]
Hi @fourjay,

`+` for corners has been the bane of my existence in the PHP version for years.

I have made the decision that I will no longer continue active development on the PHP version. A few years ago, @maruel and I started some work on a Go version, but we both dropped it on the floor. I've fixed this up over the last couple of days such that it is -- apart from custom objects -- feature complete WRT the version in this repository. The rendering is not exactly the same due to a few bugfixes (and a few unimplemented scaling things).

The [Go version](https://github.com/asciitosvg/asciitosvg) supports `+` to delimit an angled corner in a box. It also does not barf on stupidly complex diagrams by running itself out of memory. It's also much faster. Really, there are very few upsides to continuing use of the PHP version.

As such, I will be closing any issues reported, sadly starting with this one. Getting the PHP version to support `+` for corners will effectively require a rewrite of the more complicated parts of the code, and I don't really care to do that.

If you do not have any particular attachment to the PHP code, I'd recommend running `go get github.com/asciitosvg/asciitosvg/cmd/a2s` and using that instead. I am happy to merge bugfixes and features submitted externally, but I will not be doing any new development on this version of ASCIIToSVG.
